---
- name: update packages
  become: yes
  apt:
    name: "*"
    autoclean: yes
    update_cache: yes
    state: latest

- name: install packages
  become: yes
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - python-pip
    - python-dev
    - python-setuptools
    - python-virtualenv
    - git
    - libyaml-dev
    - build-essential
    - subversion
    - libjpeg62-turbo-dev
    - imagemagick
    - libav-tools
    - libv4l-dev
    - cmake
    - apache2
    - avahi-daemon
    - libavahi-compat-libdnssd1

- name: clone octoprint sources
  git:
    repo: https://github.com/foosel/OctoPrint.git
    dest: /home/pi/OctoPrint

- name: setup virtualenv
  command: "virtualenv venv"
  args:
    chdir: /home/pi/OctoPrint
    creates: /home/pi/OctoPrint/venv

- name: upgrade pip
  command: "/home/pi/OctoPrint/venv/bin/pip install pip --upgrade"
  register: pip_upgrade
  changed_when: "False == (pip_upgrade.stdout | regex_search('already up-to-date'))"

- name: find pybonjour
  stat:
    path: /home/pi/OctoPrint/venv/lib/python2.7/site-packages/pybonjour.py
  register: pybonjour
  changed_when: False

- name: install pybonjour
  command: "/home/pi/OctoPrint/venv/bin/pip install https://goo.gl/SxQZ06"
  when: 'pybonjour.stat.exists == False'

- name: install OctoPrint
  command: "/home/pi/OctoPrint/venv/bin/python setup.py install"
  args:
    chdir: /home/pi/OctoPrint
    creates: /home/pi/OctoPrint/venv/bin/octoprint

- name: clone mjpg-streamer sources
  git:
    repo: https://github.com/jacksonliam/mjpg-streamer.git
    dest: /home/pi/mjpg-streamer

- name: build mjpg-streamer
  shell: |
    LD_LIBRARY_PATH=.
    exec make
  args:
    chdir: /home/pi/mjpg-streamer/mjpg-streamer-experimental
    creates: /home/pi/mjpg-streamer/mjpg-streamer-experimental/mjpg_streamer

- name: make .octoprint and scripts dirs
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - /home/pi/.octoprint
    - /home/pi/scripts

- name: copy scripts
  copy:
    src: 'files/{{ item }}'
    dest: /home/pi/scripts/
    owner: pi
    group: pi
    mode: 0755
  with_items:
    - webcam
    - webcamDaemon

- name: copy OctoPrint systemd script
  become: yes
  copy:
    src: files/octoprint.service
    dest: /etc/systemd/system/octoprint.service
    owner: root
    group: root
    mode: 0755
  notify:
    - systemd reload
    - systemd restart octoprint

- name: copy Webcam systemd script
  become: yes
  copy:
    src: files/webcam.service
    dest: /etc/systemd/system/webcam.service
    owner: root
    group: root
    mode: 0755
  notify:
    - systemd reload
    - systemd restart webcam

- name: add pi to the dialout and tty groups
  become: yes
  user:
    name: pi
    groups: "{{ item }}"
    append: yes
  with_items:
    - dialout
    - tty

- name: is mod_proxy configured?
  stat:
    path: /etc/apache2/mods-enabled/proxy.load
  register: mod_proxy
  changed_when: False

- name: configure mod_proxy
  become: yes
  command: "a2enmod proxy"
  when: "mod_proxy.stat.exists == False"
  notify: 
    - systemd restart apache

- name: is mod_proxy_http configured?
  stat:
    path: /etc/apache2/mods-enabled/proxy_http.load
  register: mod_proxy_http
  changed_when: False

- name: configure mod_proxy_http
  become: yes
  command: "a2enmod proxy_http"
  when: "mod_proxy_http.stat.exists == False"
  notify: 
    - systemd restart apache

- name: configure apache
  become: yes
  copy:
    src: files/octoprint.conf
    dest: /etc/apache2/sites-available/octoprint.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - systemd restart apache

