---
- name: systemd reload
  become: yes
  systemd:
    daemon_reload: yes

- name: systemd restart octoprint
  become: yes
  systemd:
    name: octoprint
    enabled: yes
    state: restarted

- name: systemd restart webcam
  become: yes
  systemd:
    name: webcam
    enabled: yes
    state: restarted

- name: systemd restart apache
  become: yes
  systemd:
    name: apache2
    enabled: yes
    state: restarted

