---
server:
    host: 127.0.0.1

    # Add the rest of the config in!!!
   - action: streamon
     command: /home/pi/scripts/webcam start
     confirm: false
     name: Start video stream

   - action: streamoff
     command: /home/pi/scripts/webcam stop
     confirm: false
     name: Stop video stream
system:
  actions:
  - name: Shutdown
    command: sudo shutdown -h now
    action: shutdown
    confirm: You are about to shutdown the system.

  - name: Reboot
    command: sudo shutdown -r now
    action: reboot
    confirm: You are about to reboot the system
